# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Ingredient.create(name: "Sugar syrup")
Ingredient.create(name: "Lime juice")
Ingredient.create(name: "Lemon juice")
Ingredient.create(name: "London dry gin")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Light white rum")
Ingredient.create(name: "Angostura Aromatic Bitters")
Ingredient.create(name: "Orange juice")
Ingredient.create(name: "Triple sec liqueur")
Ingredient.create(name: "Dry vermouth")
Ingredient.create(name: "Cognac V.S.O.P.")
Ingredient.create(name: "Pineapple juice")
Ingredient.create(name: "Sweet vermouth")
Ingredient.create(name: "Bourbon whiskey")
Ingredient.create(name: "Apple juice")
Ingredient.create(name: "Pomegranate (grenadine) syrup")
Ingredient.create(name: "Tequila (reposado)")
Ingredient.create(name: "Egg white")
Ingredient.create(name: "Orange bitters")
Ingredient.create(name: "Cranberry juice (red)")
Ingredient.create(name: "Grand Marnier liqueur")
Ingredient.create(name: "Soda (club soda)")
Ingredient.create(name: "Cream")
Ingredient.create(name: "Maraschino liqueur")
Ingredient.create(name: "Blended Scotch whisky")
Ingredient.create(name: "Fresh mint leaves/sprigs")
Ingredient.create(name: "Brut champagne")
Ingredient.create(name: "Grapefruit juice (pink)")
Ingredient.create(name: "Elderflower liqueur")
Ingredient.create(name: "Absinthe")
Ingredient.create(name: "Apricot brandy liqueur")
Ingredient.create(name: "Coffee liqueur")
Ingredient.create(name: "Campari Bitter")
Ingredient.create(name: "Calvados apple brandy")
Ingredient.create(name: "Amaretto liqueur")
Ingredient.create(name: "Milk")
Ingredient.create(name: "Black raspberry liqueur")
Ingredient.create(name: "Runny honey")
Ingredient.create(name: "Bénédictine D.O.M. liqueur")
Ingredient.create(name: "White crème de cacao liqueur")
Ingredient.create(name: "Peychaud's aromatic bitters")
Ingredient.create(name: "Aged rum (+7 year old)")
Ingredient.create(name: "Citrus flavoured vodka")
Ingredient.create(name: "Chartreuse Vert (green)")
Ingredient.create(name: "Cherry brandy liqueur")
Ingredient.create(name: "Irish cream liqueur")
Ingredient.create(name: "Almond (orgeat) syrup")
Ingredient.create(name: "Cachaça")
Ingredient.create(name: "Lime cordial")
Ingredient.create(name: "Raspberries (fresh)")
Ingredient.create(name: "Golden rum")
Ingredient.create(name: "Ginger ale")
Ingredient.create(name: "Crème de cassis")
Ingredient.create(name: "Melon liqueur (green)")
Ingredient.create(name: "Galliano L'Autentico liqueur")
Ingredient.create(name: "Blue curaçao liqueur")
Ingredient.create(name: "Drambuie liqueur")
Ingredient.create(name: "Vanilla infused vodka")
Ingredient.create(name: "Straight rye whiskey")
Ingredient.create(name: "Hazelnut liqueur")
Ingredient.create(name: "Żubrówka bison grass vodka")
Ingredient.create(name: "Fino sherry")
Ingredient.create(name: "Maple syrup")
Ingredient.create(name: "Islay single malt Scotch whisky")
Ingredient.create(name: "Agave syrup")
Ingredient.create(name: "Chartreuse Jaune (yellow)")
Ingredient.create(name: "Peach Schnapps liqueur")
Ingredient.create(name: "Crème de banane liqueur")
Ingredient.create(name: "Port wine")
Ingredient.create(name: "White wine (Sauvignon Blanc)")
Ingredient.create(name: "Pisco")
Ingredient.create(name: "Apple schnapps liqueur")
Ingredient.create(name: "Ginger beer")
Ingredient.create(name: "Falernum liqueur")
Ingredient.create(name: "Lemonade/Sprite/7-Up")
Ingredient.create(name: "Coconut rum liqueur")
Ingredient.create(name: "White crème de menthe")
Ingredient.create(name: "Ginger liqueur")
Ingredient.create(name: "Southern Comfort liqueur")
Ingredient.create(name: "Dark crème de cacao liqueur")
Ingredient.create(name: "Basil leaves")
Ingredient.create(name: "Dubonnet Red")
Ingredient.create(name: "Passion fruit syrup")
Ingredient.create(name: "Jenever")
Ingredient.create(name: "Vodka raspberry flavoured")
Ingredient.create(name: "Sake")
Ingredient.create(name: "Overproof rum (white)")
Ingredient.create(name: "Strawberries (fresh)")
Ingredient.create(name: "Ginger (fresh root)")
Ingredient.create(name: "Navy rum")
Ingredient.create(name: "Prosecco sparkling wine")
Ingredient.create(name: "Vanilla sugar syrup")
Ingredient.create(name: "Passion fruit (fresh)")
Ingredient.create(name: "Lillet Blanc")
Ingredient.create(name: "Honey sugar syrup")
Ingredient.create(name: "Espresso coffee (freshly made)")
Ingredient.create(name: "Black pepper")
Ingredient.create(name: "Tonic water")
Ingredient.create(name: "Anise liqueur")
Ingredient.create(name: "Crème de framboise liqueur")